name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync backend repository with VPS
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: backend/
          remote_path: /var/www/portfolio/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_port: ${{ secrets.VPS_PORT }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSHKEY }}
